branches:
  only:
    - master
    - dev

language: node_js

node_js:
  - 12

install:
  - yarn install
  - pip install --user awscli

script:
  - yarn type-check
  - test $TRAVIS_BRANCH = "master" && GATSBY_ACTIVE_ENV=production || GATSBY_ACTIVE_ENV=staging
  - GATSBY_ACTIVE_ENV=$GATSBY_ACTIVE_ENV yarn build:app

before_deploy:
  - export SCRIPT_COUNTER=$(($SCRIPT_COUNTER+1))
  - >
    if (( $SCRIPT_COUNTER == 1 )); then
      yarn global add serverless
      chmod -R +x ./travis/bin
    fi

deploy:
  - provider: script
    script: travis/bin/deploy.sh $AWS_S3_BUCKET $AWS_CLOUDFRONT_DISTRIBUTION_ID
    skip_cleanup: true
    on:
      all_branches: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET
    local_dir: public
    skip_cleanup: true
    on:
      all_branches: true
