service: mx-dessertsathome-web

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

plugins:
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'

package:
  exclude:
    - ./**
  include:
    - aws/functions/**

custom:
  domain:
    dev: staging.postresadomicilio.mx
    prod: postresadomicilio.mx

resources:
  Resources:
    DessertsAtHomeWebBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
    DessertsAtHomeWebCloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: DessertsAtHomeWebCloudFrontOriginAccessIdentity
    DessertsAtHomeWebBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref DessertsAtHomeWebBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                CononicalUser: !GetAtt
                DessertsAtHomeWebCloudFrontOriginAccessIdentity.S3CanonicalUserId
              Action: s3.GetObject
              Resource:
                !Join ['', ['arn:aws:s3:::', !Ref DessertsAtHomeWebBucket, /*]]
            - Effect: Allow
              Principal: s3.ListBucket
              Resource:
                !Join ['', ['arn:aws:s3:::', !Ref DessertsAtHomeWebBucket]]
    DessertsAtHomeDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: mx-dessertsathome-web-${self:provider.stage}
          Origins:
            - Id: DessertsAtHomeWebOrigin
              DomainName: !GetAtt DessertsAtHomeWebBucket.DomainName
              S3OriginConfig:
                OriginAccessIdentity:
                  !Join ['', [origin-access-identity/cloudfront/, !Ref DessertsAtHomeWebCloudFrontOriginAccessIdentity]]
          PriceClass: PriceClass_100
          DefaultRootObject: index.html
          HttpVersion: http2
          Aliases:
            - ${self:custom.domain.${self:provider.stage}}
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:139557914541:certificate/5ed5ba7b-f163-4c25-a668-92fb5094c047
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.1_2016
          DefaultCacheBehavior:
            TargetOriginId: DessertsAtHomeWebOrigin
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          CustomErrorResponses:
            - ErrorCode: 400
              ErrorCachingMinTTL: 300
              ResponseCode: 200
              ResponsePagePath: '/index.html'
            - ErrorCode: 404
              ErrorCachingMinTTL: 300
              ResponseCode: 200
              ResponsePagePath: '/index.html'
            - ErrorCode: 405
              ErrorCachingMinTTL: 300
              ResponseCode: 200
              ResponsePagePath: '/index.html'

  